- name: does kubeadm config exist on the system
  stat:
    path: /etc/kubernetes/pki/ca.crt
  register: kubeadm_config_status

- name: set variable based on file existence
  set_fact:
    kubeadm_config_exists: "{{ kubeadm_config_status.stat.exists | default(false) }}"

- name: Get join command from master
  set_fact:
    join_command: "{{ hostvars[groups['master'][0]]['join_command'] }}"
  when: not kubeadm_config_status.stat.exists
  
- name: Join the k8s cluster
  command: "{{ join_command }}"
  when: not kubeadm_config_status.stat.exists
