# - name: Cleanup to run again
#   command: |
#     rm /etc/apt/sources.list.d/cri-o.list
#     rm /etc/apt/keyrings/cri-o-apt-keyring.gpg
#     rm /etc/apt/sources.list.d/kubernetes.list
#     rm /etc/apt/keyrings/kubernetes-apt-keyring.gpg
#   become: yes
#   ignore_errors: yes
#
- name: Update and upgrade APT packages
  apt:
    update_cache: yes
  changed_when: false

- name: Disable Swap
  command: swapoff -a
  changed_when: false

- name: permanent swap disable
  replace:
    path: /etc/fstab
    regexp: '^\s*(.*\s+swap\s+.*)$'
    replace: '#\1'
  changed_when: false

- name: Load Modules at bootup
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  changed_when: false

- name: Load Kernel Modules
  modprobe:
    name: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter
  changed_when: false

- name: Apply sysctl params required by setup, params persist across reboots
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  changed_when: false

- name: Apply sysctl params without reboot
  command: sysctl --system
  changed_when: false

- name: Install required packages
  apt:
    name:
      - software-properties-common
      - curl
      - apt-transport-https
      - curl
      - gpg
      - ca-certificates
    state: present
    update_cache: yes
  become: yes

- name: Downloading CRIO release key and generating gpg
  shell: curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/cri-o-apt-keyring.gpg
  become: yes

- name: Adding repo to apt
  shell: echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/ /" | tee /etc/apt/sources.list.d/cri-o.list
  args:
    creates: /etc/apt/sources.list.d/cri-o.list
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false
 
- name: Install CRI-O
  apt:
    name: cri-o
    state: present
    update_cache: yes

- name: Enable and start CRIO service
  systemd:
    name: crio.service
    state: started
    enabled: yes
  become: yes

- name: Add K8s GPG Key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: yes

- name: Add K8s Repo
  shell: |
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
  args:
    creates: /etc/apt/sources.list.d/kubernetes.list
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  changed_when: false

- name: Install K8s components
  package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Prevent Automatic updates for kubelet, kubeadm and kubectl
  command:
    cmd: apt-mark hold kubelet kubeadm kubectl
  changed_when: false
