services:
  db_blog:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: blogDB
    volumes:
      - ./blog_data:/var/lib/postgresql/data

  blog:
    image: derekshaw/blogmicro:1.0
    depends_on:
      - db_blog
    environment:
      DATABASE_URL: "postgresql://postgres:example@db_blog/blogDB"
    entrypoint: ["/app/wait-for.sh", "db_blog:5432", "--", "/app/start.sh"]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  
  nginx:
    image: nginx:latest
    depends_on:
      - blog
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  frontend:
    image: derekshaw/frontend:0.0
    command: ["npm", "run", "dev"]
