- name: Gather Master Node IP
  command: curl ifconfig.me
  register: master_ip_raw

- name: Set Master Node IP
  set_fact:
    master_ip: "{{ master_ip_raw.stdout.split(' ')[0] }}"

# - name: Reset kubeadm before init
#   shell: yes | kubeadm reset
#   become: yes
#
- name: Initialize k8s cluster
  command: kubeadm init --control-plane-endpoint="{{ master_ip }}" --apiserver-cert-extra-sans="{{ master_ip }}" --pod-network-cidr="{{ pod_network_cidr }}" --ignore-preflight-errors Swap
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf
  become: yes

# - name: Create .kube directory
#   file:
#     path: /home/{{ ansible_user }}/.kube
#     state: directory
#     mode: 0755
#   become_user: "{{ ansible_user }}"
#
# - name: Copy admin.conf to user's kube config
#   copy:
#     src: /etc/kubernetes/admin.conf
#     dest: /home/{{ ansible_user }}/.kube/config
#     remote_src: yes
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  run_once: true
  become: yes

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command.stdout }}"
  run_once: true

- name: Configure Kubeconfig
  shell: |
    mkdir -p "$HOME"/.kube
    cp -i /etc/kubernetes/admin.conf "$HOME"/.kube/config
    chown "$(id -u)":"$(id -g)" "$HOME"/.kube/config
  become: yes
  args:
    creates: "{{ ansible_env.HOME }}/.kube/config"
  ignore_errors: yes

# - name: Create the .kube directory in the user's home
#   become: yes
#   file:
#     path: "{{ ansible_env.HOME }}/.kube"
#     state: directory
#     mode: '0755'
#
# - name: Copy the Kubernetes admin config to user's kube directory
#   become: yes
#   copy:
#     src: /etc/kubernetes/admin.conf
#     dest: "{{ ansible_env.HOME }}/.kube/config"
#     owner: "{{ ansible_user_id }}"
#     group: "{{ ansible_user_gid }}"
#     mode: '0644'
#
# - name: Change ownership of the kubeconfig file
#   become: yes
#   file:
#     path: "{{ ansible_env.HOME }}/.kube/config"
#     owner: "{{ ansible_user_id }}"
#     group: "{{ ansible_user_gid }}"
#     mode: '0644'
