apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeissuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ranjanshivesh71@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kubeissuer
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert
spec:
  secretName: mycert
  issuerRef:
    name: kubeissuer
    kind: ClusterIssuer
  commonName: derekshaw.mooo.com
  dnsNames:
  - derekshaw.mooo.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-route
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - derekshaw.mooo.com
    secretName: mycert
  rules:
  - host: derekshaw.mooo.com
    http:
      paths:
      - path: /backend(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
