apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-blog-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: ./blog_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-blog-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-auth-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: ./auth_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
