apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authdb-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: db-auth
  policyTypes:
    - Ingress
    - Egress
